import DocumentsTable from "@/components/documents-table";
import { Layout } from "antd";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Content>
        <DocumentsTable />
      </Layout.Content>
    </Layout>
  );
};

export default Home;
